# This is a sample build configuration for Java (Maven).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: maven:3.6.1

pipelines:
  branches:
    release/dockerhub:
      - step:
          services:
            - docker
          caches:
            - maven
          script:
            - mvn -B install
            - cd AccountsMicroservice
            - MVN_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
            - ACCOUNT_VERSION=(${MVN_VERSION//-/ })
            - export ACCOUNTS_IMAGE_NAME=markpost/bank-demo-accounts:$ACCOUNT_VERSION
            - docker build -t $ACCOUNTS_IMAGE_NAME .
            - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            - docker push $ACCOUNTS_IMAGE_NAME

