version: '3.3'

services:
  # Accounts Microservice
  accounts-microservice:
    depends_on:
      - eureka-microservice
      - accounts-microservice-db
      - kafka
    image: markpost/accounts-microservice:0.1
    container_name: acounts-microservice
    ports:
      - "7701:7701"
    restart: always
    build:
      context: ./AccountsMicroservice
      dockerfile: Dockerfile
    volumes:
      - /data/accounts-microservice
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://accounts-microservice-db/bank-accounts?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=accounts-user
      - SPRING_DATASOURCE_PASSWORD=123456
    networks:
      - bank-demo-microservices-net
  # Database Accounts Microservice
  accounts-microservice-db:
    image: mysql:8
    container_name: acounts-microservice-db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
    volumes:
      - accounts-microservice-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bank-accounts
      MYSQL_USER: accounts-user
      MYSQL_PASSWORD: 123456
    networks:
      - bank-demo-microservices-net

  # ApiGateway Microservice
  api-gateway-microservice:
    depends_on:
      - eureka-microservice
    image: markpost/api-gateway-microservice:0.1
    container_name: api-gateway-microservice
    ports:
      - "7700:7700"
    restart: always
    build:
      context: ./ApiGatewayMicroservice
      dockerfile: Dockerfile
    volumes:
      - /data/api-gateway-microservice
    networks:
      - bank-demo-microservices-net

  # Clients Microservice
  clients-microservice:
    depends_on:
      - eureka-microservice
      - clients-microservice-db
      - kafka
    image: markpost/clients-microservice:0.1
    container_name: clients-microservice
    ports:
      - "7702:7702"
    restart: always
    build:
      context: ./ClientsMicroservice
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://clients-microservice-db/bank-clients?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=clients-user
      - SPRING_DATASOURCE_PASSWORD=123456
    volumes:
      - /data/clients-microservice
    networks:
      - bank-demo-microservices-net
  # Database Clients Microservice
  clients-microservice-db:
    image: mysql:8
    container_name: clients-microservice-db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3308:3306
    volumes:
      - clients-microservice-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bank-clients
      MYSQL_USER: clients-user
      MYSQL_PASSWORD: 123456
    networks:
      - bank-demo-microservices-net

  # Eureka Microservice
  eureka-microservice:
    image: markpost/eureka-microservice:0.1
    container_name: eureka-microservice
    ports:
      - "7799:7799"
    restart: always
    build:
      context: ./EurekaMicroservice
      dockerfile: Dockerfile
    volumes:
      - /data/eureka-microservice
    networks:
      - bank-demo-microservices-net

  # Transactions Microservice
  transactions-microservice:
    depends_on:
      - eureka-microservice
      - transactions-microservice-db
      - kafka
    image: markpost/transactions-microservice:0.1
    container_name: transactions-microservice
    ports:
      - "7703:7703"
    restart: always
    build:
      context: ./TransactionsMicroservice
      dockerfile: Dockerfile
    volumes:
      - /data/transactions-microservice
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://transactions-microservice-db/bank-transactions?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=transactions-user
      - SPRING_DATASOURCE_PASSWORD=123456
    networks:
      - bank-demo-microservices-net
  # Database Transactions Microservice
  transactions-microservice-db:
    image: mysql:8
    container_name: transactions-microservice-db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3309:3306
    volumes:
      - transactions-microservice-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bank-transactions
      MYSQL_USER: transactions-user
      MYSQL_PASSWORD: 123456
    networks:
      - bank-demo-microservices-net

  # Zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    networks:
      - bank-demo-microservices-net

  # Kafke
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    networks:
      - bank-demo-microservices-net

networks:
  bank-demo-microservices-net:

volumes:
  accounts-microservice:
  accounts-microservice-db:
  api-gateway-microservice:
  clients-microservice:
  clients-microservice-db:
  eureka-microservice:
  transactions-microservice:
  transactions-microservice-db: